// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf0lytJ5zKRVmha9UooOYf874f183KqKU',
    appId: '1:253467842526:web:34e99d08b04091767a6f4f',
    messagingSenderId: '253467842526',
    projectId: 'fir-memo-app-26a9d',
    authDomain: 'fir-memo-app-26a9d.firebaseapp.com',
    storageBucket: 'fir-memo-app-26a9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-Bf7uCyyvHvdJAV-OlxR3Y1LSC2W1C4',
    appId: '1:253467842526:android:1d2da2ec8ca0f8ad7a6f4f',
    messagingSenderId: '253467842526',
    projectId: 'fir-memo-app-26a9d',
    storageBucket: 'fir-memo-app-26a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvgrmu7qnbtgs7nmxysLSlAyYpKDIOVis',
    appId: '1:253467842526:ios:4d85a1e4819be4e27a6f4f',
    messagingSenderId: '253467842526',
    projectId: 'fir-memo-app-26a9d',
    storageBucket: 'fir-memo-app-26a9d.appspot.com',
    iosBundleId: 'com.example.test3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvgrmu7qnbtgs7nmxysLSlAyYpKDIOVis',
    appId: '1:253467842526:ios:fefcba48c3cd4a277a6f4f',
    messagingSenderId: '253467842526',
    projectId: 'fir-memo-app-26a9d',
    storageBucket: 'fir-memo-app-26a9d.appspot.com',
    iosBundleId: 'com.example.test3App.RunnerTests',
  );
}
